### ISSUE TITLE
Implement more of the common interface

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/Sundials.jl#109]
More of Sundials can be exposed to the common interface, specifically using the Sundials commands:

- [x] CVodeSetMinStep
- [x] CVodeSetMaxStep

to set the values from `dtmax` and `dtmin`. The `Algorithm` types can be upgraded to hold options for stability limit detection and choosing the number of nonlinear iterations.

- [x] CVodeSetstabLimDet
- [x] CVodeSetMaxNonlinIters

`tstops` can get a full implementation via:

- [x] CVodeSetStopTime

Then, the integrator interface can be implemented on the Sundials common interface, allowing for callbacks. The callbacks would have to call

- [ ] CVodeReInit

after resetting the state to apply event handling.

The progressbar part of the interface will also be added, covering https://github.com/JuliaDiffEq/Sundials.jl/issues/40

None of this is particularly difficult (those are the commands from the Sundials C documentation to look up) so if anyone wants to help implement this I could give pointers. The end result will have Sundials pretty feature complete to the common interface, with easy event handling, callbacks, and most of the options. (However, Sundials will still be limited to problems which don't change size and Float64, but those are limitations of Sundials itself).

**Comment by tshort** [comment]
`resize!` could be implemented. It could just re-initialize the problem and copy over `u` and `du`. I did that for "structural events" in [Sims](https://github.com/tshort/Sims.jl). A tricky part of `resize!` is that the user may have to make sure the problem still solves after the size change.

**Comment by ChrisRackauckas** [comment]
Well, the manual says you can't resize with `CVodeReInit`. Do you mean you created a whole new `mem`? The problem here is that, wouldn't you also have to start back at Euler? Of course, we can get it all working so the user could make the choice, but this sounds both like something that isn't easy to get working well and even if it did, it wouldn't be a very efficient algorithm.

**Comment by tshort** [comment]
Completely restart with new mem. I didn't say it would be efficient:). For some problems, that may be acceptable.

**Comment by ChrisRackauckas** [comment]
Sure, we can do that. I'd probably just be setting it up for the purpose of being able to destroy it in benchmarks, but even that has value.

**Comment by ChrisRackauckas** [comment]
Just a note for event handling. After digging through the event handling implementation, I think it's better to do the implementation similar to OrdinaryDiffEq.jl and directly use the interpolations. CVode/IDA use a version of the Illinois algorithm in the Hiebert & Shampine method, but it doesn't offer much safety. It doesn't use interpolation checks for multiple roots though, and its active/inactive root states means that consecutive roots can be an issue. 

So because Sundials internally uses Illinois instead of Bisection, it may be slightly faster in some cases than using Roots, but I think a better option is just to set it up with Roots and eventually some Julia false position method will be implemented which will be just as fast. And this part really isn't a performance trap anyways. So long term the speed will be fine, but this option is safer and integrates better with the rest of the API.
