### ISSUE TITLE
Sundials CVODE_BDF() not freeing memory

### ISSUE THREAD

**Issue by robindenhardteriksson** [JuliaDiffEq/Sundials.jl#111]
I've noticed large memory usage of the julia process when repeatedly calling the CVODE_BDF solver. Repeatedly calling the following code gives this behaviour on my machine, I can see the memory usage steadily increase. In order to run the code model.jl and data.jld are provided in the zip.
For some background, I've been using evolutionary algorithms (Evolutionary.jl) to try and fit a system of ODEs, hence the repeated calling of the integrator. Similar to repeatedly calling the code, integrator results are replaced at every generation, hence old results and ODEProblem objects should freed.

```
using DifferentialEquations
using JLD
include("model.jl") # system of ODEs

function callode( expr, timeMatrix ) # function calling Sundials.jl (through DifferentialEquations.jl)

T2SS = (0.0, timeMatrix[1] ) # time to steady state
IC = zeros(27) # initial conditions
IC[1] = 2.25
IC[2] = 0.93
IC[5] = 1.04
IC[6] = 6.06
IC[7] = 1
pmodel = ParameterizedFunction( model, expr )
prob = ODEProblem( pmodel, IC, T2SS )
sol = solve( prob, CVODE_BDF(), abstol=1e-10, reltol=1e-8 )

  return sol.u[end] # return solution at final time point
end

iter = 10000 # number of times to perform integration
expr = load("data.jld","expr") # load user data
timeMatrix = [500.0 ]
yss = zeros(iter,27)

for j = 1:iter
     yss[j,:] = callode(expr,timeMatrix)
end

```
[Archive.zip](https://github.com/JuliaDiffEq/Sundials.jl/files/816316/Archive.zip)

**Comment by ChrisRackauckas** [comment]
It's only growing by about 2-3MB each time and it seems to clear when I call the `gc()`. Are you sure it just hasn't triggered the garbage collector?

**Comment by ChrisRackauckas** [comment]
Can anyone confirm a memory problem?

**Comment by tpoisot** [comment]
For me, `gc()` was not solving it. And after running ~10⁶ simulations, it amounts to quite a lot of memory.

**Comment by ChrisRackauckas** [comment]
This same example? Do you have an MWE you can share?

**Comment by tpoisot** [comment]
Not this example -- no MVE anymore, since we moved to other packages for numerical integration bc of the issue.

**Comment by ChrisRackauckas** [comment]
If you find it again, please let me know! I would like to get this fixed, but I can't seem to reproduce it.

**Comment by ChrisRackauckas** [comment]
This should solve it: https://github.com/JuliaDiffEq/Sundials.jl/pull/112 . That registers the Sundials pointers to the GC and should make it much more robust at least. If a leak still exists after that merges, open a new issue please with an MWE.

**Comment by ChrisRackauckas** [comment]
#112
