### ISSUE TITLE
Sundials Build Error trying to download

### ISSUE THREAD

**Issue by SCR1** [JuliaDiffEq/Sundials.jl#121]
Getting an error when I try to build Sundials. I'm guessing its a permissions issue of some sort as I'm trying to do this on a work laptop that is heavily locked down with a firewall.

Any hints?

```
Pkg.add("Sundials")
INFO: No packages to install, update or remove
INFO: Package database updated
Pkg.build("Sundials")
INFO: Building Sundials
INFO: Attempting to Create directory C:\Users\scr1\.julia\v0.5\Sundials\deps\downloads
INFO: Directory C:\Users\scr1\.julia\v0.5\Sundials\deps\downloads already created
INFO: Downloading file https://cache.julialang.org/https://bintray.com/artifact/download/tkelman/generic/sundials-2.5.0.7z
Exception calling "DownloadFile" with "2" argument(s): "The request was 
aborted: Could not create SSL/TLS secure channel."
At line:1 char:1
+ (new-object 
net.webclient).DownloadFile("https://cache.julialang.org/https://bin ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException
 
==============================[ ERROR: Sundials ]===============================

LoadError: failed process: Process(`'C:\Windows\System32\WindowsPowerShell\v1.0\powershell' -NoProfile -Command '(new-object net.webclient).DownloadFile("https://cache.julialang.org/https://bintray.com/artifact/download/tkelman/generic/sundials-2.5.0.7z", "C:\Users\scr1\.julia\v0.5\Sundials\deps\downloads\sundials-2.5.0.7z")'`, ProcessExited(1)) [1]
while loading C:\Users\scr1\.julia\v0.5\Sundials\deps\build.jl, in expression starting on line 37

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: Sundials had build errors.

 - packages with build errors remain installed in C:\Users\scr1\.julia\v0.5
 - build the package(s) and all dependencies with `Pkg.build("Sundials")`
 - build a single package by running its `deps/build.jl` script

================================================================================
```

**Comment by tkelman** [comment]
we rebuilt a new version of cache.julialang.org recently (cc @staticfloat), maybe your powershell download has issue with the certificates? try removing the cache.julialang.org prefix from the url, see if that helps

**Comment by SCR1** [comment]
Nailed it. That fixed it.

**Comment by tkelman** [comment]
note that Pkg.status() will probably show the package as dirty, you'll need to undo the modifications if you want to get future updates from Pkg.update()

**Comment by tkelman** [comment]
I think bintray has been reliable enough that maybe caching isn't necessary here, but when I moved the binaries from sourceforge to bintray I wasn't sure yet whether that would be the case (sourceforge was definitely down every few days and needed caching)

**Comment by ChrisRackauckas** [comment]
So do we need to change

```julia
provides(Binaries, URI("https://cache.julialang.org/https://bintray.com/artifact/download/tkelman/generic/$sundialsver.7z"),
    sundialslibs, unpacked_dir="usr$(Sys.WORD_SIZE)/bin", os = :Windows)
```

to

```julia
provides(Binaries, URI("https://bintray.com/artifact/download/tkelman/generic/$sundialsver.7z"),
    sundialslibs, unpacked_dir="usr$(Sys.WORD_SIZE)/bin", os = :Windows)
```

**Comment by tkelman** [comment]
yeah I think that would make sense here. for the sake of other cases where caching is more necessary we should try to work out what's wrong with the certificates though, if we can

**Comment by tkelman** [comment]
@SCR1 just to clarify this was still happening now? when was the last time you ran it? a few days ago the certs did need tweaking, so if it was before than then maybe it was fixed.

**Comment by SCR1** [comment]
@tkelman I had never gotten it installed or running before. This was my first try.  We have weird cert things going on with my work machine so I wouldn't be surprised if that is it. I'm probably an edge case?

**Comment by tkelman** [comment]
I hope so. Several other packages are using the same caching server and actually need it, so keep us posted if you hit this anywhere else.
