### ISSUE TITLE
build failing due to Hash mismatch

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaDiffEq/Sundials.jl#157]
```julia
INFO: Calculated hash cc15c458d73fb32d406c4e88b1478e0a1eaaf90a4675d91241224c3121ace343 for file /Users/solver/.julia/v0.6/Sundials/deps/usr/downloads/Sundials.x86_64-apple-darwin14.tar.gz
==================================================================================[ ERROR: Sundials ]==================================================================================

LoadError: Hash Mismatch!
  Expected sha256:   7c9b0a73c334c9e7cd3b7b43a6df8c9275feb7fd02c7240e3804ea29a50dbedb
  Calculated sha256: cc15c458d73fb32d406c4e88b1478e0a1eaaf90a4675d91241224c3121ace343
while loading /Users/solver/.julia/v0.6/Sundials/deps/build.jl, in expression starting on line 56
```

**Comment by ChrisRackauckas** [comment]
This is a BinaryProvider.jl bug. It doesn't knew to get rid of the old binary on MacOS. (I guess there's a downside to being an early adopter of BinDeps2.)

https://discourse.julialang.org/t/hash-mismatch-on-latest-sundials/9128/2

Just go in and delete it and you'll be good.

**Comment by dlfivefifty** [comment]
deleting /Users/solver/.julia/v0.6/Sundials/deps/usr/downloads/Sundials.x86_64-apple-darwin14.tar.gz

fixed the problem

**Comment by robinde** [comment]
Same problem, same solution on ubuntu 17.10.

**Comment by ChrisRackauckas** [comment]
Okay. @staticfloat is there any way this can be fixed?

**Comment by staticfloat** [comment]
Oh, sorry, I thought I had already fixed this particular issue.

https://github.com/JuliaPackaging/BinaryProvider.jl/pull/38 should do it; once that's merged the `build.jl` within this repository should "just work".
