### ISSUE TITLE
Setup mass matrices with ARKODE

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/Sundials.jl#160]
@OliverEvans96 pointed out that he wanted to use ARKODE with mass matrices and currently that's not setup. It would just require checking for a mass matrix in the ODEProblem and if it has one, converting it to a Sundials matrix and passing it through the API call.

**Comment by jondeuce** [comment]
Hi @ChrisRackauckas 

Is there any progress on this issue? I would also be interested in using this feature, particularly with sparse mass matrices.

**Comment by ChrisRackauckas** [comment]
Hey, sorry. I ended up getting very busy. This isn't too difficult of an issue though so I am hoping it will get done if there's a student who's interested in starting work on Sundials.jl for GSoC. If not, I can knock it out sometime in January. Give it a bump then if you're still interested. It should be only around 10 lines of code so it's a great beginner issue but I also don't want to delay someone's research if I can find the hour or so to do it.

**Comment by jondeuce** [comment]
Hi @ChrisRackauckas,

Thanks for working on this! I've been trying to get the solver working for systems of the form `M*du = K*u`, where `M` and `K` are constant sparse matrices, but I've run into some issues. A minimal example is:
```julia
M = randn(3,3) |> sparse
K = copy(M)
u0 = ones(3)
tspan = (0.0, 1.0)
f! = (du,u,p,t) -> mul!(du, K, u)
u_analytic = (u0,p,t) -> exp.(u0.*t)

odefun = ODEFunction{true,true}(f!, analytic = u_analytic, mass_matrix = M, jac_prototype = K)
prob = ODEProblem(odefun, u0, tspan)
sol = solve(prob, ARKODE(linear_solver = :KLU, mass_linear_solver = :KLU), u0, tspan)
```
The issue, as far as I can tell, is two-fold:
1. The `ARKODE` constructor doesn't allow using `:KLU` for the `linear_solver` or `mass_linear_solver`. It does look to be implemented, though, so I think it just hasn't been added to the list of allowed solvers.
2. Manually adding `:KLU` to the allowed solvers, I then get the following `ARKODE` error:
```
[ARKODE ERROR]  arkInitialSetup
  The mass matrix solver's setup routine failed.
```
And I've not been able to resolve this. Any help would be much appreciated!

**Comment by ChrisRackauckas** [comment]
I don't know why that would occur either. It would take some digging. Maybe the mass matrix isn't what's passed down to the right constructor, so it doesn't build a sparse SUNMatrix? One would need to take a deep look at what's being passed where in the solve.jl code.

**Comment by jondeuce** [comment]
Okay, I'll do some digging when I have the time then. I'll let you know if I figure it out, possibly just by making a PR if it's a simple enough fix.
