### ISSUE TITLE
IDAFree throws error

### ISSUE THREAD

**Issue by Mattri** [JuliaDiffEq/Sundials.jl#167]
When Initializing IDA with `a=Sundials.IDACreate()` and trying to de-allocate space with `Sundials.IDAFree(mem)`, I receive the following error:

ERROR: MethodError: no method matching IDAFree(::Ptr{Sundials.IDAMem})
Closest candidates are:
  IDAFree(::Ref{Ptr{Sundials.IDAMem}}) at d:\Julia_Repo\v0.6\Sundials\src\idas.j
l:866

I'm using Sundials v0.14.0 and Julia 0.6

**Comment by Mattri** [comment]
Sorry, I missed the update. Now, I'm on v1.5.1 and everything is fine (after having figured out the syntax modifications ;-))

**Comment by ChrisRackauckas** [comment]
Great! Let me know if you need anything else.
