### ISSUE TITLE
Not building in JuliaPro-0.6.2.1

### ISSUE THREAD

**Issue by mattcbro** [JuliaDiffEq/Sundials.jl#168]
On my linux mint 18.3 juliapro-0.6.2 installation,  I can not build this package.  I get the following:

julia> Pkg.build("Sundials")
INFO: Building SpecialFunctions
INFO: Building DiffEqBase
INFO: ~~~ DifferentialEquations.jl *BREAKING* changes  ~~~

We have changed the front-end API on how
users may define equations of motion and 
problems, for all problem types that can
be used in the DifferentialEquations.jl.
These are *BREAKING* changes, and they
also have *NO WARNINGS*!

Please see our latest documentation here:
http://docs.juliadiffeq.org/latest/

or the blogpost that describes the changes:
http://juliadiffeq.org/2018/01/24/Parameters.html

In short, the mutated argument is the first argument,
and parameters are now directly passed
into the equations of motion function. For all
types now mutation goes first, then dependent variables, 
then parameters, then independent variables. 

`f(mutated, dependent variables, p/integrator, independent variables)`

For example, this means that the ODE syntax will be `f(u,p,t)` (for the
out-of-place) and `f(du,u,p,t)` (for the in-place). Notice
that this change also removes the need for ParameterizedFunctions
as now parameters are part of the equations of motion.

For more details please visit the above links!
INFO: Building Sundials
=====================================================================[ ERROR: Sundials ]======================================================================

LoadError: MethodError: no method matching BinaryProvider.LibraryProduct(::BinaryProvider.Prefix, ::Array{String,1}, ::Symbol)
Closest candidates are:
  BinaryProvider.LibraryProduct(::BinaryProvider.Prefix, ::Array{S<:AbstractString,1}) where S<:AbstractString at /home/matt/programs/juliapro/JuliaPro-0.6.2.1/JuliaPro/pkgs-0.6.2.1/v0.6/BinaryProvider/src/Products.jl:42
  BinaryProvider.LibraryProduct(::BinaryProvider.Prefix, ::AbstractString) at /home/matt/programs/juliapro/JuliaPro-0.6.2.1/JuliaPro/pkgs-0.6.2.1/v0.6/BinaryProvider/src/Products.jl:38
  BinaryProvider.LibraryProduct(::AbstractString, ::Array{S<:AbstractString,1}) where S<:AbstractString at /home/matt/programs/juliapro/JuliaPro-0.6.2.1/JuliaPro/pkgs-0.6.2.1/v0.6/BinaryProvider/src/Products.jl:56
while loading /home/matt/programs/juliapro/JuliaPro-0.6.2.1/JuliaPro/pkgs-0.6.2.1/v0.6/Sundials/deps/build.jl, in expression starting on line 6

==============================================================================================================================================================

=======================================================================[ BUILD ERRORS ]=======================================================================

WARNING: Sundials had build errors.

 - packages with build errors remain installed in /home/matt/programs/juliapro/JuliaPro-0.6.2.1/JuliaPro/pkgs-0.6.2.1/v0.6
 - build the package(s) and all dependencies with `Pkg.build("Sundials")`
 - build a single package by running its `deps/build.jl` script

==============================================================================================================================================================

**Comment by ChrisRackauckas** [comment]
You are on an old version of JuliaPro. You need JuliaPro v0.6.2.2 which will fix this issue. See this issue for more details:

https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/265
