### ISSUE TITLE
CVODES tests are segfaulting on v0.7

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/Sundials.jl#177]
On v0.6 they were fine, showing the the wrapper is fine. The issue is the test setup. Something about how we're wrapping one of the `cfunction`s is not v0.7-compatible. I tried a bit and couldn't figure it out.

pinging @axsk since it was your code I was trying to update.

**Comment by axsk** [comment]
Thanks for the attempt, I'm looking at it now.

**Comment by ViralBShah** [comment]
Maybe reopen if still an issue?
