### ISSUE TITLE
SparseArrays not in its dependencies

### ISSUE THREAD

**Issue by MartinOtter** [JuliaDiffEq/Sundials.jl#183]
Wenn upgrading ModiaMath to the newest Sundials version, the following warning appears:

```julia
Importing ModiaMath version 0.2.2 (2018-09-18)
┌ Warning: Package Sundials does not have SparseArrays in its dependencies:
│ - If you have Sundials checked out for development and have
│   added SparseArrays as a dependency but haven't updated your primary
│   environment's manifest file, try `Pkg.resolve()`.
│ - Otherwise you may need to report an issue with Sundials
└ Loading SparseArrays into Sundials from project dependency, future warnings for Sundials are suppressed.
┌ Warning: The call to compilecache failed to create a usable precompiled cache file for ModiaMath [80923050-9e1b-11e8-0c9e-c9f8e684994a]
│   exception = Required dependency Sundials [c3572dad-4567-51f8-b174-8c6c989267f4] failed to load from a cache file.
└ @ Base loading.jl:963
```

I guess SparseArrays needs to be added to the Require/Project.toml file of Sundials

**Comment by ChrisRackauckas** [comment]
There was a bad commit to Julia's package repository. It's described a bit here.

https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/350#issuecomment-423025342

It's not a Sundials or DiffEq thing, it effects any repository that had a tag after some specific time. So it's an upstream issue but Stefan knows about it and is fixing it. There's more discussion in the Slack #helpdesk channel.

**Comment by MartinOtter** [comment]
Thanks for the information. I just tried again, but got the same effect (I stopped working on ModiaMath/Modia3D with Julia for the moment, since too tedious to work with).

Do you have information, when this will be fixed (I do not use Slack, so I cannot follow)?

**Comment by ChrisRackauckas** [comment]
Some of the Slack conversation:

Kristoffer Carlsson [Yesterday at 7:40 PM]
@stefan it seems your commit to the registry dropped the stdlibs deps from the latest versions for a bunch of packages, e.g. (https://github.com/JuliaRegistries/General/commit/c6032b203253268dc7151064fff5158da81b3b84#diff-60ad0b44e938d9b35732a3e174a29627) (edited)
 


12 replies
Stefan Karpinski [11 hours ago]
If only we knew what code had been generating registries before, this would be significantly easier to debug


Stefan Karpinski [11 hours ago]
All I’m doing is running the code that is on master with no cap


Aykut Satici [2 hours ago]
Is there a quick fix to offer even though it might be ugly?
I have a paper to submit on Monday and I need to be running the code...


Stefan Karpinski [2 hours ago]
you can always revert the `~/.julia/registries/General` repo to something from yesterday


Aykut Satici [2 hours ago]
Thanks Stefan.


Aykut Satici [43 minutes ago]
I did `git reset --hard HEAD~100`, but I still get the myriad of warnings...

Stefan Karpinski [22 minutes ago]
If you have a working manifest checked in you can always revert to that


Stefan Karpinski [22 minutes ago]
Rolling back the registry out to do it


Stefan Karpinski [22 minutes ago]
You may want to post the actual output in #pkg-usage


Aykut Satici [21 minutes ago]
Will do, thanks again!


Aykut Satici [3 minutes ago]
Switching to an older Manifest file worked.


Aykut Satici [3 minutes ago]
Just as a reference to whomever might be facing the same issue.

**Comment by atombear** [comment]
i'm sorry if this is an understood problem, but i suddenly started seeing this today. is there a solution?

**Comment by ChrisRackauckas** [comment]
Someone needs to wake up and merge https://github.com/JuliaRegistries/General/pull/521

**Comment by atombear** [comment]
i see. that looks quite recent.

**Comment by ChrisRackauckas** [comment]
If you update this should be fixed. Sorry about that: just switched over to Project.tomls and missed some standard library parts
