### ISSUE TITLE
SavingCallback and solver options

### ISSUE THREAD

**Issue by ivborissov** [JuliaDiffEq/Sundials.jl#200]
Hi,
The following worked for me in Julia 0.7
```
f = (du, u, p, t) -> du[1] = u[1]
prob = ODEProblem(f,[1.0],(0.0,1.0))
out = SavedValues(Float64, Vector{Float64})
scb = SavingCallback((u,t,integrator)->[2*u[1]], out, saveat = [0.0,0.25,0.5,0.75,1.0])
sol = solve(prob,CVODE_BDF(),  save_start=false, save_end=false, save_everystep=false, callback=scb)
```
now it produces an error:
`ERROR: BoundsError: attempt to access 0-element Array{Float64,1} at index [0]` which points to 
https://github.com/JuliaDiffEq/Sundials.jl/blob/master/src/common_interface/integrator_utils.jl#L33

Without saving options everything workes fine:
`solve(prob,CVODE_BDF(), callback=scb)`

It seems to be related to these changes
https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/pull/514

However my initial setup workes fine with other solvers but `Sundials`. Should I use some other combination instead of `save_start=false, save_end=false, save_everystep=false`?

**Comment by ChrisRackauckas** [comment]
Was just a bug, fixed by that commit.

**Comment by ivborissov** [comment]
Thanks!
