### ISSUE TITLE
Warn in checkflag macro

### ISSUE THREAD

**Issue by ivborissov** [JuliaDiffEq/Sundials.jl#202]
Hi, 
Should it be `@warn` here?
https://github.com/JuliaDiffEq/Sundials.jl/blob/master/src/simple.jl#L20

**Comment by ChrisRackauckas** [comment]
yes, I think that should be `@warn` on v1.0.

**Comment by ChrisRackauckas** [comment]
Oh, this was fixed awhile ago.
