### ISSUE TITLE
SavingCallback used with ContinousCallback error

### ISSUE THREAD

**Issue by ivborissov** [JuliaDiffEq/Sundials.jl#203]
Hi, 
Even after this correction https://github.com/JuliaDiffEq/Sundials.jl/issues/202
the following code still produces an error. Julia solvers (e.x. `Tsit5`) handle this setup correctly.
```
f = (du, u, p, t) -> du[1] = u[1]
out = SavedValues(Float64, Vector{Float64})
scb = SavingCallback((u,t,integrator)->[2*u[1]], out, saveat = [0.0,0.25,0.5,0.75,1.0])
condition = (u,t,integrator) -> t-0.7
function affect!(integrator)
    save_affect! = integrator.opts.callback.discrete_callbacks[1].affect!
    save_affect!(integrator, true)
    integrator.u[1] = 1.0
    save_affect!(integrator, true)
end
cb = CallbackSet(scb, ContinuousCallback(condition,affect!,(integrator) -> nothing,save_positions=(false,false)))
prob = ODEProblem(f,[1.0],(0.0,1.0),callback = cb)
sol = solve(prob,CVODE_BDF(),  save_start=false, save_end=false, save_everystep=false)

[CVODES ERROR]  CVodeGetDky
  Illegal value for t.t = 0.725424 is not between tcur - hu = 0.760925 and tcur = 0.928816.

┌ Warning: CVodeGetDky failed with error code =
│   flag = -25
└ @ Sundials C:\Julia-1.1.0\packages\Sundials\eAJ5O\src\simple.jl:20

```

**Comment by ChrisRackauckas** [comment]
`condition = (u,t,integrator) -> t-0.7` is causing it to always trigger at `t=0.7` and then `saveat = [0.0,0.25,0.5,0.75,1.0]` wants to interpolate back to zero which isn't in the interval. This is just a bad idea and the integrator interface mentions that you shouldn't be interpolating out of the current interval. Instead, you should trigger at each interval passing a saveat value, which is exactly what the saving callback does in practice if you just use it directly.

**Comment by ivborissov** [comment]
Chris, could you please give me an example how to rewrite it in the intended way. My goal is to save some values `f(u,t,integrator)` at `saveat` timepoints. When I use events I also need to call  `save_affect!` function before and after the `affect!`. I understand the interpolation problem here but what is the proper way to handle it?

**Comment by ChrisRackauckas** [comment]
You need to trigger the SavingCallback at each step separately from the continuous one, and then just trigger the save_affect! before the internal effect of the SavingCallback

**Comment by ivborissov** [comment]
Sorry, could you please give me an example how it should look like

**Comment by ChrisRackauckas** [comment]
Oh that might be a little difficult 🤷‍♂ . You might want to essentially put the saving callback code into a callback, i.e. fancy interpolations + calling `savevalues!` directly.

**Comment by ivborissov** [comment]
Though it is not related to `Sundials` (maybe we better move this talk elsewhere), I'll be grateful if you help me better understand the way `SavingCallback` and `Continuous/Discrete  Callback` should be used together. Now I use the following code (workaround):

```
function affect!(integrator)
    save_affect! = integrator.opts.callback.discrete_callbacks[1].affect!
    save_before_after(save_affect!, integrator)
    # change some parameter values
    save_before_after(save_affect!, integrator)
end

function save_before_after(
    affect!::DiffEqCallbacks.SavingAffect,
    integrator
)
    affect!.saveiter += 1
    copyat_or_push!(affect!.saved_values.t, affect!.saveiter, integrator.t)
    copyat_or_push!(affect!.saved_values.saveval, affect!.saveiter, affect!.save_func(integrator.u, integrator.t, integrator),Val{false})
end
```
Is it an ok solution or there can be issues with it? I am still a bit confused about the intended way to handle this problem))

**Comment by ChrisRackauckas** [comment]
When I did this in PuMaS, directly without SavingCallback, I used the difference between `savevalues!(integrator)` vs `savevalues!(integrator,true)` (forcing a save), with `save_everystep=false`, using the first to trigger saveat while the second is to then just save at a point. I assume something similar would be needed here, so maybe SavingCallback needs a PR, but this is something that is quite intricate.
