### ISSUE TITLE
Error building `Sundials`: in julia 1.1.0

### ISSUE THREAD

**Issue by wzz1999** [JuliaDiffEq/Sundials.jl#204]
julia> import Pkg; Pkg.build("Sundials")
  Building Sundials → `C:\Users\wzz\.julia\packages\Sundials\eAJ5O\dep
s\build.log`
┌ Error: Error building `Sundials`:
│ ┌ Warning: On Windows, creating file symlinks requires Administrator
privileges
│ └ @ Base.Filesystem file.jl:794
│ ┌ Warning: platform_key() is deprecated, use platform_key_abi() from
now on
│ │   caller = ip:0x0
│ └ @ Core :-1
│ [ Info: Downloading https://github.com/JuliaDiffEq/SundialsBuilder/releases/download/sundials-3.1.1.6/Sundials.v1.0.0.x86_64-w64-mingw32.tar.gz to C:\Users\wzz\.julia\packages\Sundials\eAJ5O\deps\usr\downloads\Sundials.v1.0.0.x86_64-w64-mingw32.tar.gz...
│ ERROR: LoadError: Could not download https://github.com/JuliaDiffEq/SundialsBuilder/releases/download/sundials-3.1.1.6/Sundials.v1.0.0.x86_64-w64-mingw32.tar.gz to C:\Users\wzz\.julia\packages\Sundials\eAJ5O\deps\usr\downloads\Sundials.v1.0.0.x86_64-w64-mingw32.tar.gz:
│ ErrorException("")
│ Stacktrace:
│  [1] error(::String) at .\error.jl:33
│  [2] #download#93(::Bool, ::Function, ::String, ::String) at C:\Users\wzz\.julia\packages\BinaryProvider\4F5Hq\src\PlatformEngines.jl:498
│  [3] #download at .\none:0 [inlined]
│  [4] #download_verify#94(::Bool, ::Bool, ::Bool, ::Function, ::String, ::String, ::String) at C:\Users\wzz\.julia\packages\BinaryProvider\4F5Hq\src\PlatformEngines.jl:567
│  [5] #download_verify at .\none:0 [inlined]
│  [6] #install#133(::Prefix, ::String, ::Bool, ::Bool, ::Bool, ::Function, ::String, ::String) at C:\Users\wzz\.julia\packages\BinaryProvider\4F5Hq\src\Prefix.jl:314
│  [7] (::getfield(BinaryProvider, Symbol("#kw##install")))(::NamedTuple{(:prefix, :force, :verbose),Tuple{Prefix,Bool,Bool}}, ::typeof(install), ::String, ::String) at .\none:0
│  [8] top-level scope at C:\Users\wzz\.julia\packages\Sundials\eAJ5O\deps\build.jl:53
│  [9] include at .\boot.jl:326 [inlined]
│  [10] include_relative(::Module, ::String) at .\loading.jl:1038
│  [11] include(::Module, ::String) at .\sysimg.jl:29
│  [12] include(::String) at .\client.jl:403
│  [13] top-level scope at none:0
│ in expression starting at C:\Users\wzz\.julia\packages\Sundials\eAJ5O\deps\build.jl:49
│ ʹ�á�2���������á�DownloadFile��ʱ�����쳣:����
WebClient �����ڼ�
│ �����쳣����
│ ����λ�� ��:5 �ַ�: 1
│ + $webclient.DownloadFile("https://github.com/JuliaDiffEq/SundialsBuil
│ d ...
│ + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
│ ~
│     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationE
│    xception
│     + FullyQualifiedErrorId : WebException
│
└ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.1\Pkg\src\Operations.jl:1075

**Comment by ChrisRackauckas** [comment]
It thought that was fixed a long time ago by BinaryBuilder? Is this an old version of Julia?

**Comment by wzz1999** [comment]
I installed it on Julia 1.0.3

**Comment by wzz1999** [comment]
> 它认为很久以前BinaryBuilder修复了吗？这是朱莉娅的旧版本吗？

I installed it on Julia 1.0.3

**Comment by wzz1999** [comment]
Successful build after deleting Julia 1.0.3
