### ISSUE TITLE
Memory leaks in N_Vector and cvode

### ISSUE THREAD

**Issue by rs1909** [JuliaDiffEq/Sundials.jl#24]
1) when a julia vector is converted into NVector, the conversion code allocates the NVector structure, but this is never freed.

To solve this, automatic conversion should be disabled and each conversion should be followed by a call to N_VDestroy_Serial

2) when CVodeCreate is called it allocates memory for internal use, but it is never freed.
This memory should be freed using CVodeFree

These two leaks fill up memory quite quickly if one calculates say bifurcation diagrams....

Thanks for the code, it is rather useful otherwise.

**Comment by ChrisRackauckas** [comment]
Closed due to #67
