### ISSUE TITLE
How to pass user_data argument of f to the solver

### ISSUE THREAD

**Issue by scidom** [JuliaDiffEq/Sundials.jl#3]
Hi Tom, perhaps I should not report this as an issue, since it is more of a question as to how to use one of your package's functionalities. I want to pass an extra argument to `f`, which you call `user_data` in  examples/cvode_Roberts_dns.jl (and is of type `Ptr{Void}`). I will use the CVODE solver and I don't know how this `user_data` argument of `f` will be passed to CVODE ultimately - does the package support this functionality? As an example, I simply simulated the ODE system below via `Sundials.ode` (and circumvented the problem by wrapping `f2` in `f`). In this example, the parameters `p = [a, b, c]` play the role of `user_data`. Any hints as to whether it is possible to pass them to CVODE via your package will be valuable. Here is the simple example (Fitzhugh-Nagumo ODE system, consisting of 2 ODEs):

``` julia
# Simulate data from the Fitzhugh-Nagumo ODEs
# d/dt(V) = c*(R+V-V^3/3)
# d/dt(R) = -(V-a+R*b)/c

using Sundials

function f2(t, y, ydot, p)    
    ydot[1] = p[3]*(y[2]+y[1]-y[1]^3/3)
    ydot[2] = -(y[1]-p[1]+y[2]*p[2])/p[3]
end

# Time t
t = [i for i in 0.:10]

# Initial conditions y0 = [V, R]
y0 = [-1., 1.];

# Parameters p = [a, b, c]
p = [0.2, 0.2, 3];

f(t, y, ydot) = f2(t, y, ydot, p)

data = Sundials.ode(f, y0, t)
```

**Comment by ChrisRackauckas** [comment]
This has been pretty much been made obsolete by fast closures in v0.5:

```julia
g = (t,u,du) -> f(t,u,du,p)
```

or using ParameterizedFunctions.jl (or wrapper functions, or the user_data).
