### ISSUE TITLE
Segmentation Fault on CVodeF

### ISSUE THREAD

**Issue by gasagna** [JuliaDiffEq/Sundials.jl#33]
Hi, 

likely it is my fault here but I cannot figure out what is wrong in my code. I am trying to use Sundials api to solve an adjoint sensitivity problem. The culprit is this line:

``` julia
flag = Sundials.CVodeF(cvode_mem, t[2], [t[1]], tret, Sundials.CV_NORMAL, Int32[0])
```

which I derived from the line

``` julia
flag = Sundials.CVode(cvode_mem, t[i], tmp, tret, Sundials.CV_NORMAL)
```

of the basic interface. Initialisation of the adjoint problem, via `CVodeAdjInit` is successfull.

The code segfault with this error message

```
signal (11): Segmentation fault
N_VClone at /home/davide/.julia/v0.3/Sundials/deps/usr/lib/libsundials_cvodes.so (unknown line)
```

Any hints?

Davide

**Comment by ikirill** [comment]
I'm getting a similar segfault, but inside `CVodeB`, with backtrace looking like this:

      * frame #0: 0x000000030c4c603c libsundials_cvodes.dylib`CVodeB [inlined] CVAdataStore(ck_mem=0x000000030d435690) + 1670 at cvodea.c:2054
        frame #1: 0x000000030c4c59b6 libsundials_cvodes.dylib`CVodeB(cvode_mem=0x0000000102617e00, tBout=<unavailable>, itaskB=1) + 1046 at cvodea.c:1402

I don't have a debugging version of sundials yet. Before the segfault there is a large number of error messages of the form

    [CVODES ERROR]  CVodeGetDky
      Illegal value for t.t = 476.672 is not between tcur - hu = 309.148 and tcur = 320.308.

but this might not be related.

This doesn't seem to be related to cvode/cvodes name clash because my libsundials_cvode equals libsundials_cvodes

**Comment by ikirill** [comment]
Actually, it's possible that my segfault is Sundials's fault, not Sundials.jl's.

**Comment by ChrisRackauckas** [comment]
The binaries and everything changed so I'm not sure this is relevant anymore.
