### ISSUE TITLE
Should sundials functions return Julia symbols instead of integer (enum) flags?

### ISSUE THREAD

**Issue by ikirill** [JuliaDiffEq/Sundials.jl#37]
It seems to me the interface would be cleaner if:
- when a Sundials function returns `CV_SUCCESS` (= 0), it would return `:CV_SUCCESS` instead of integer 0, and similarly for any other non-error informational flag
- when a Sundials function returns `CV_ILL_INPUT` (or some other flag that means an error), it would raise an error instead of returning an integer

Is there a reason why this isn't done in Sundials.jl? In my own code I have some macros to do this kind of error-checking automatically, and it seems like this would improve the interface.

If the issue is with exactly duplicating the C interface, then maybe put wrapped functions into a separate module?

**Comment by acroy** [comment]
I agree that the error handling should be improved. In the "high-level" functions in `src/Sundials.jl` we should probably throw appropriate exceptions when an error occurs. Those could contain the error code. What would be the advantage of using symbols instead of error codes? We could have a dictionary to store the error messages for each code, which would be shown if an exception occurs (this way we avoid overhead due to storing the message in the exception type).

**Comment by ikirill** [comment]
> What would be the advantage of using symbols instead of error codes?

With a symbol you have some idea of what it means, like `:CV_SUCCESS` clearly means success, or `:CV_ILL_INPUT`. With an integer, you know that `0` really means success, and `-22` means illegal input, but only because you have some special list of enum values to compare it with. If you "forget" where the integer came from (e.g., `CV_*` or `CVDLS_*`), you can't really tell what it means any more. A symbol, on the other hand, keeps all the necessary information with it (e.g., you can easily distinguish `CV_SUCCESS` from `CVDLS_SUCCESS`, whatever the second one is).

Plus, you can't display a C enum value in an error message; messages like `CVODES failed: -22` are terrible, but `CVODES failed with :CV_ILL_INPUT` is fine.

> We could have a dictionary to store the error messages for each code

With integers, this doesn't quite work because some return values have slightly different meanings but map to the same integer. You can only tell them apart if you also happen to know which function they came from.

The way I have it in my code is there's a set of `CV_check`, `CVDIAG_check` macros that convert flags to symbols/errors, one function that maps symbols to long error strings, and one error type 

    type SundialsError 
        value::Symbol
    end

with a `Base.showerror` method that displays a long message when a SundialsError is printed.

**Comment by acroy** [comment]
If you check locally (i.e. after a function call) you also know if you have to compare to the constant `CV_SUCCESS` or `CVDLS_SUCCESS`. There I don't see an issue. If you want to address error propagation (i.e. you don't know from which function the error came), it is probably better to have a macro, which knows the type of function called, and emit an appropriate exception. We could have `CVException` and `CVDLSException` and so on. Depending on the exception type `Base.showerror` can then pick the right messages.

I haven't checked this, but I can imagine that symbols actually introduce some overhead. In the REPL for simple problems this probably doesn't matter, but if you call the Sundials functions very often it might be relevant?

**Comment by ikirill** [comment]
> If you check locally (i.e. after a function call) you also know if you have to compare to the constant CV_SUCCESS or CVDLS_SUCCESS.

Yes, but why make this extra "restriction" of checking locally? If it returns :CV_SUCCESS, the extra information about the function's return value is stored in the function's return value.

> ...We could have CVException and CVDLSException and so on....

It's not like this wouldn't work, but then you would have to do the same thing for successful return types too. For example, there are seven constants in constants.jl with the value 3. Why make the user of the interface do the extra work of remembering which flag came from where, when the function itself can return exactly the right thing and no extra work needs to be done?

> I haven't checked this, but I can imagine that symbols actually introduce some overhead.

A symbol is represented internally as an integer, and when a symbol is created by name, that name is looked up in a global table (https://github.com/JuliaLang/julia/blob/69b84e94ead99fe7f0017a1dc4ac263f6a07b09f/src/alloc.c#L556). There is no meaningful overhead in using symbols for special return values. See also how NLopt handles enums and symbols (https://github.com/JuliaOpt/NLopt.jl/blob/master/src/NLopt.jl#L116, https://github.com/JuliaOpt/NLopt.jl/blob/master/src/NLopt.jl#L512)

> if you call the Sundials functions very often it might be relevant

Sundials is not designed to be called often, it's designed to be called on very large complicated problems. Look, for example, at how much care it takes to solve very large systems of linear equations efficiently.

**Comment by acroy** [comment]
Well, if NLopt does this my nitpicking is apparently unfounded. It would be great if you could provide a PR to discuss the details.

**Comment by ChrisRackauckas** [comment]
Fixed by common retcodes
