### ISSUE TITLE
CVODES examples and support (cvsRoberts_FSA_dns)

### ISSUE THREAD

**Issue by ikirill** [JuliaDiffEq/Sundials.jl#38]
What is the state of support for forward/adjoint sensitivity analysis? The examples seem to be missing, and there is the comment

```
# IDAS  (still incomplete)
```

in https://github.com/JuliaLang/Sundials.jl/blob/master/src/Sundials.jl#L200, which seems suspicious.

The type of `CVodeSensInit` (https://github.com/JuliaLang/Sundials.jl/blob/master/src/Sundials.jl#L200) seems wrong, as it makes a vector out of `yS0`, where C function expects a pointer to an array of N_Vectors.

I'm not demanding that it must be implemented, it's just that it's missing from the readme's todo-list, and the readme seems to say that it should work, yet it looks only partially implemented.

**Comment by acroy** [comment]
I don't know to what extent people have used sensitivity analysis and Sundials.jl (might be worth to ask on the mailinglist). The low level functions are basically there (in `src/cvodes.jl` and `src/idas.jl`), but the "convenience" functions in `src/Sundials.jl` are incomplete. I think PRs to improve this situation will be highly appreciated :-)

**Comment by benmoran** [comment]
I'd love an example to see how this should work as well.

**Comment by christianhaargaard** [comment]
Anything new on this? I would love to see a simple example of how to do the forward sensitivity analysis. I have used Sundials in C before for sensitivity analysis, but I haven't quite got the programming skills to figure out how to do the calls correctly in Julia (at least I haven't figured it out yet).

**Comment by acroy** [comment]
Unfortunately not. It seems no one of the maintainers has sufficient experience with forward sensitivity analysis to tackle this. I can't promise anything, but maybe if you post a small example in C (maybe as gist or just here) someone can help to translate it to Julia.

**Comment by christianhaargaard** [comment]
Alright, was just hoping someone might have a minimal working example. I will try and see if I can convert the simplest example from Sundials to Sundials.jl. I might be back with more questions :-)
Thanks for the answer.

**Comment by christianhaargaard** [comment]
So, I have been trying to implement the simple `cvsRoberts_FSA_dns.c` example, and I have managed to make it run. Like ikirill stated above, line 127-130 are wrong. I have only used the function `CVodeSensInit1` as it is the one used in the example. The lines currently are
```julia
CVodeSensInit(mem, Ns, ism, fS::Function, yS0) =
    CVodeSensInit(mem, Ns, ism, cfunction(fS, Int32, (int32, realtype, N_Vector, N_Vector, N_Vector, N_Vector, Ptr{Void}, N_Vector, N_Vector)), nvector(yS0))
CVodeSensInit1(mem, Ns, ism, fS1::Function, yS0) =
    CVodeSensInit1(mem, Ns, ism, cfunction(fS1, Int32, (int32, realtype, N_Vector, N_Vector, int32, N_Vector, N_Vector, Ptr{Void}, N_Vector, N_Vector)), nvector(yS0))
```
but as ikirill stated the Sundials libraries expect `yS` to be a pointer to an array of N_Vectors. The correct code (Pasting for the one I used, guesstimating for the other one) would be
```julia
CVodeSensInit(mem, Ns, ism, fS::Function, yS0) =
    CVodeSensInit(mem, Ns, ism, cfunction(fS, Int32, (Int32, realtype, N_Vector, N_Vector, N_Vector, N_Vector, Ptr{Void}, N_Vector, N_Vector)), yS0)
CVodeSensInit1(mem, Ns, ism, fS1::Function, yS0) =
    CVodeSensInit1(mem, Ns, ism, cfunction(fS1, Int32, (Int32, realtype, N_Vector, N_Vector, Int32, N_Vector, N_Vector, Ptr{Void}, N_Vector, N_Vector)), yS0)
```
Note, that in addition to removing the call to make an N_Vector of `yS0`, the argument type for the cfunction call has also been changed from int32 to Int32.

Changing the definition of `CVodeSensInit1` like this, I can create `yS` by (I'm sure there are better ways, but this works so far)
```julia
ySJ = Array(Array{Float64,1}, neq)
ySJ[1] = zeros(Float64,3)
ySJ[2] = zeros(Float64,3)
ySJ[3] = zeros(Float64,3)

ySjulia = [Sundials.nvector(ySJ[1]), Sundials.nvector(ySJ[2]), Sundials.nvector(ySJ[3])]
yS = pointer(ySjulia)
```
and then initialize it by
```julia
CVodeSensInit1(mem, NS, iS, fS, yS)
```.

During the solver-loops I can then fetch the sensitivities by doing
```julia
while iout<nout # =1, tout=T1; iout <= NOUT; iout++, tout *= TMULT) {
  flag = Sundials.CVode(cvode_mem, tout, y, t, Sundials.CV_NORMAL)
  flag = Sundials.CVodeGetSens(cvode_mem, t, yS);
  tempyS = [unsafe_load(yS,1), unsafe_load(yS,2), unsafe_load(yS,3)]
  
  println("T = ", tout, ", Y = ", y)
  println("Sens1: ", Sundials.asarray(tempyS[1]))
  println("Sens2: ", Sundials.asarray(tempyS[2]))
  println("Sens3: ", Sundials.asarray(tempyS[3]))
```

Just wanted to share my progress. I'm no expert on the calls to C, and how to handle the pointers correctly, so please let me know if there are obvious mistakes/improvements to be made.

If you think I should I can spend a little time figuring out how to get github setup properly, so I can submit the changes myself. I will also keep working on the examples, as I think the sensitivy-capabilities would be useful tool to have in the packages.

**Comment by christianhaargaard** [comment]
I ended up making my own fork. I made the changes and added the example as well, and it works. The output is not exactly equal to the the one posted with the C-code, but it's quite close. I noticed that the other examples are a little off as well.
I have made a pull-request for the changes from my fork.

**Comment by benmoran** [comment]
Thanks for this Christian, your example runs for me.

**Comment by christianhaargaard** [comment]
Thanks for testing it. I have also created an example where Sundials uses finite differences estimates for the Jacobian for the sensitivities. Let me know if that has interest.

**Comment by axsk** [comment]
I also tried building a (at least concerning code lines) simpler example, but the code returns an
``` julia
[CVODES ERROR]  CVode
  At t = 0 and h = 1.3093e-11, the corrector convergence test failed repeatedly or with |h| = hmin.
```

Maybe someone experienced (@christianhaargaard) can spot an error?
Here is my code
``` julia
using Sundials

# y[1]'' = - p[1]^2 * y[1]
function f(t, y, ydot, user_data)
    y       = Sundials.asarray(y)
    ydot    = Sundials.asarray(ydot)
    p = unsafe_pointer_to_objref(user_data)
    
    ydot[1] = y[2] * p[1]
    ydot[2] = -y[1] * p[1]
    return Int32(0)
end

y = [sin(pi/4), cos(pi/4)]
p = [sqrt(1/2)]

neq = length(y)
t0 = 0.0

# Create CVODES object
mem = Sundials.CVodeCreate(Sundials.CV_ADAMS, Sundials.CV_FUNCTIONAL) #nonstiff
#mem = Sundials.CVodeCreate(Sundials.CV_BDF, Sundials.CV_NEWTON) #stiff
Sundials.CVodeInit(mem, f, t0, y)

# se tolerances
reltol = 1e-2
abstol = [1e-3]
Sundials.CVodeSVtolerances(mem, reltol, abstol)

# set parameters
Sundials.CVodeSetUserData(mem, p)

# set linear solver
Sundials.CVDense(mem, neq)

# initial sensivities dy0/dp
yS = [Sundials.nvector(zeros(Float64,neq)) for i in 1:length(p)] |> pointer

# use difference quotients for sens rhs
fS = Ptr{Void}(0)

# initialize sens. analysis
Sundials.CVodeSensInit(mem, length(p), Sundials.CV_SIMULTANEOUS, fS, yS)

# automatically estimate tolerances
Sundials.CVodeSensEEtolerances(mem)

# dont use sens variables in error tests
Sundials.CVodeSetSensErrCon(mem, 0);

# indices of parameters for sens. analysis
plist = Int32[0]

# register parameters for sens. analysis
Sundials.CVodeSetSensParams(mem, p, p, plist |> pointer)

t = [0.]
tstop  = 0.1

Sundials.CVode(mem, tstop, y, t, Sundials.CV_NORMAL)
```

**Comment by axsk** [comment]
I put together this [gist](https://gist.github.com/axsk/5d1e3d49a53ce331e5ef6e7daec23b8d) which offers a low level `cvodes` function similar to `cvode` for the forward sens. problem.
For convenience (in my use case) theres also `sens` which takes a parametric rhs, computes the necessary derivatives via forwarddiff and returns the solution as well as the sensivities wrt to the parameters _as well as the initial conditions_.

**Comment by ChrisRackauckas** [comment]
Thanks! I added this as a test so we can make sure it keeps working. This shows that the wrapper is all setup to do this and anyone can make use of this as they please, so I'm closing this.
