### ISSUE TITLE
CVodeReInit arguments

### ISSUE THREAD

**Issue by heflwi** [JuliaDiffEq/Sundials.jl#43]
It looks as if there's a glitch in the CVodeReInit syntax in Sundials.jl [lines 102-3]: the second argument needs to be removed (after which it seems to work ok in a trivial test example).

[Caveat: I'm new to Julia, just having a play as a possible addition to/replacement of my Matlab/Octave needs. Also never used github before, so pls forgive wrong approach/lack of a PR.]

**Comment by ViralBShah** [comment]
I am not a user of Sundials, but it would help if you could post the code example that breaks?

**Comment by tshort** [comment]
I'm not a user of CVode, but I think @heflwi is correct. The fix looks easy enough to do with github's built-in editing features. This will automatically create a pull request.

**Comment by heflwi** [comment]
Thanks for guidance - PR #44 now submitted.

**Comment by ChrisRackauckas** [comment]
This is now well-tested by the event handling interface so it's clear it works.
