### ISSUE TITLE
Type of CVodeUserDataB is wrong

### ISSUE THREAD

**Issue by ikirill** [JuliaDiffEq/Sundials.jl#46]
When trying to pass a Julia value as user data, I get a missing method error for `convert(::Type{Ptr{Union()}}, ::MyType)` Sundials expects it to be an opaque pointer to some user data that then gets passed to other user-specified functions.

In https://github.com/JuliaLang/Sundials.jl/blob/master/src/cvodes.jl#L126: the second `void*` argument is an opaque pointer to user data, much like CVodeUserData, and should be declared the same way it's set in https://github.com/ikirill/Sundials.jl/blob/master/src/Sundials.jl#L255

The definition of CVodeUserData in cvode.jl (https://github.com/JuliaLang/Sundials.jl/blob/master/src/cvode.jl#L247) has the same problem, I think, but it's overridden by https://github.com/ikirill/Sundials.jl/blob/master/src/Sundials.jl#L255

**Comment by acroy** [comment]
Looks right. I think the definitions in `Sundials.jl` should basically replace those in `cvode(s).jl` and so on.

**Comment by acroy** [comment]
Is this still a problem? Could you provide an example how this function should be used? Maybe we can include it in one of the examples ...

**Comment by ChrisRackauckas** [comment]
I'm not sure this is an issue anymore. Please reopen if it is.
