### ISSUE TITLE
Segmentation fault when passing data stored in Dictionary to user function

### ISSUE THREAD

**Issue by Mattri** [JuliaDiffEq/Sundials.jl#66]
The issue I'm describing here is somewhat similar to the one described in #3 . 
As in that case, I try to pass additional parameters to my user function. However, the data is not stored in a Vector, but in a dictionary. It works fine with KINSOL:

Initialization of solver:

`flag = Sundials.KINInit(kmem, cfunction(wuet_stat, Int32, (Sundials.N_Vector, Sundials.N_Vector, Dict{AbstractString,Any})), nvector(y))`

_wuet_stat_ is the user function, additional data is stored in a dictionary called _pass_data_ 

`flag = Sundials.KINSetUserData(kmem, pass_data)`

The header of my user function looks like this:
`function wuet_stat(u_in, fu_in, dict_in)`

Now, I tried to implement the same strategy in a dynamic model using IDA as solver:

Initialization of solver:

`flag = Sundials.IDAInit(mem, cfunction(wuet, Int32,
                                           (Sundials.realtype, Sundials.N_Vector, Sundials.N_Vector, Sundials.N_Vector, Dict{ASCIIString,Any})),
                            time[1], nvector(u), nvector(up))`

with IDASetUserData and my user function set up in the same way as in the case with KINSOL as solver. When I try to access the dictionary from the user function, the julia REPL terminates instantly, throwing a segmentation fault. Any idea, what needs to be done to the Sundials interface?

**Comment by ChrisRackauckas** [comment]
Our new interfaces are able to handle this kind of stuff just fine using things like closures, so I'm closing this as something doesn't need action anymore.
