### ISSUE TITLE
segfault using sundials functions

### ISSUE THREAD

**Issue by gasagna** [JuliaDiffEq/Sundials.jl#81]
I am having a hard time identifying a segfault in a custom code using the wrapped functions of Sundials. The gist is [here](https://gist.github.com/gasagna/abfe4f22d197154b1412a531cd0b4f04).

I am running the latest Sundials master and julia 0.4.6. I get this output

```julia
...
40[-6.6548489117029055,-10.320613520158005,17.61112044600523]
41[-9.676631014457783,-2.3993127613313825,35.58702934024834]
42[0.6108481014146323,2.7269241610824544,22.475214727745026]
43[1.894340014416633,3.3799990331837733,10.90024308001776]

signal (11): Segmentation fault: 11
fcallback at /Users/davide/Codes/SamplesGenerators.jl/src/tmp.jl:25
jlcapi_fcallback_21488 at  (unknown line)
cvStep at /Users/davide/.julia/v0.4/Sundials/deps/usr/lib/libsundials_cvodes.dylib (unknown line)
CVode at /Users/davide/.julia/v0.4/Sundials/deps/usr/lib/libsundials_cvodes.dylib (unknown line)
__CVode at /Users/davide/.julia/v0.4/Sundials/src/cvodes.jl:416
jlcall___CVode_21501 at  (unknown line)
jl_apply at /Users/davide/Software/julia/src/./julia.h:1331
next at /Users/davide/Codes/SamplesGenerators.jl/src/tmp.jl:81
jlcall_next_21500 at  (unknown line)
jl_apply at /Users/davide/Software/julia/src/./julia.h:1331
anonymous at no file:0
jl_apply at /Users/davide/Software/julia/src/toplevel.c:544
jl_parse_eval_all at /Users/davide/Software/julia/src/toplevel.c:577
jl_load at /Users/davide/Software/julia/src/toplevel.c:619
include at ./boot.jl:261
jl_apply at /Users/davide/Software/julia/src/./julia.h:1331
include_from_node1 at ./loading.jl:320
jl_apply at /Users/davide/Software/julia/src/./julia.h:1331
process_options at ./client.jl:284
_start at ./client.jl:378
jlcall__start_18875 at /Users/davide/Software/julia-0.4/usr/lib/julia/sys.dylib (unknown line)
jl_apply at /Users/davide/Software/julia/src/./julia.h:1331
true_main at /Users/davide/Software/julia-0.4/usr/bin/julia (unknown line)
main at /Users/davide/Software/julia-0.4/usr/bin/julia (unknown line)
```

Any help is appreciated.

(I am actually hitting this while developing a way to pass the rhs jacobian, quadrature functions and root identification functions in a single shot...)

**Comment by gasagna** [comment]
I have found why the crash occurs.

Essentially the instance of the ODEProblem type that is passed to Sundials as user data gets garbage collected at some point, so Sundials crashes. To fix this, `prob` must be stored permanently as an additional field of the `JuliaCVode` type. 

This might be useful in case the simple interface get overhauled...

**Comment by ChrisRackauckas** [comment]
Should keep this open until this is fixed in the simplified interface.

**Comment by acroy** [comment]
The issue reported here is not due to Sundials though - unless I missed something. Moreover, there is already #79 for passing the jacobian ...

**Comment by ChrisRackauckas** [comment]
Oh I see. I thought he was saying something inside the simplified interface was letting things get GC'd. Now that I take a closer look at it, I see what he means.

**Comment by rveltz** [comment]
@gasagna  I have several questions if I may. Indeed, I may have a similar issue with [LSODA.jl](https://github.com/rveltz/LSODA.jl)

- How did you find that the instance of the ODEProblem type is the issue?

- Also, is your [code](https://gist.github.com/gasagna/abfe4f22d197154b1412a531cd0b4f04) the one that crashes (it does not when I try)? If yes, what do you have to change to make it stable. If No, where i the buggy vereion?

Thank you for your help,

**Comment by ChrisRackauckas** [comment]
>Also, is your code the one that crashes (it does not when I try)? If yes, what do you have to change to make it stable. If No, where i the buggy vereion?

This bug report was done with v0.4.6. I wonder if it was related to a Julia GC bug. But since it is a GC bug, it might be non-deterministic. However, I ran it a bunch of times in a row (in a loop) and still didn't get a crash.

But at the same time, there seems to be almost the opposite problem now: https://github.com/JuliaDiffEq/Sundials.jl/issues/111

**Comment by rveltz** [comment]
OK, thank you

**Comment by ChrisRackauckas** [comment]
Could you open an issue for the LSODA.jl bug? I am interested in tracking that.

**Comment by rveltz** [comment]
I will. I just need to find a simple example because it is non-deterministic, it might be a GC issue as well.
