### ISSUE TITLE
Documentation: `integrator` is a keyword argument, not positional for `cvode`

### ISSUE THREAD

**Issue by mobius-eng** [JuliaDiffEq/Sundials.jl#83]
README states:

> For `cvode`, there is an optional positional argument `integrator` to choose between the two provided integration options: `:BDF` for a Backwards Differentiation Formula method and `:Adams` for an Adams-Moulton method. 

However, function `cvode` does not have this as a positional argument.

**Comment by acroy** [comment]
README on github reflects the documentation for the current master and /not/ for the version last tagged ( I found this confusing myself). To get the latest version just use `Pkg.checkout("Sundials")`.

**Comment by mobius-eng** [comment]
True, I just saw it in sources. However, it's still not positional argument, it is a keyword argument.

**Comment by ChrisRackauckas** [comment]
It is. I changed the README in the upcoming PR to reflect this. Thanks for informing us.

**Comment by ChrisRackauckas** [comment]
Updated.
