### ISSUE TITLE
matrix free method

### ISSUE THREAD

**Issue by rveltz** [JuliaDiffEq/Sundials.jl#92]
Hi,

I am wondering if the matrix free method is available. According to the manual, the user should provide CVSPILS linear solver a function `CVSpilsSetPreconditioner`.

Thank you for your help,

Best regards

**Comment by ChrisRackauckas** [comment]
If it requires a newer version of Sundials, then what's needed is #77 / #89. If this functionality is in the version of Sundials already wrapped, then all of the parts should be available (though they might be untested)
