### ISSUE TITLE
More Refined Algorithm Choices for Common Interface

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/Sundials.jl#97]
Now that there is the common interface, more refined algorithm choices can occur from in the same general `solve` command. Some different examples of things would be:

- Changing solver option. Right now the recommended defaults are used (`BDF` with Newton, and `Adams` with Functional). There are many reasons to switch this around, for example @AlexanderKoshkarov ran into memory issues with the Newton solver, so the way around that was to use the functional iteration because that doesn't require the linear solver. Allowing for more algorithm choices will enable users to do this without having to dig into the codes.
- Exposing the linear solver interface. This portion will be more difficult. Right now the common interface exposes only the dense solver (like the simple interface). For example, in most cases people likely want to use the banded solver for discretized PDEs which will be faster and more memory efficient than the dense solver. However, this will also mean exposing the right options as keyword arguments and documenting them appropriately. This will be a bit more work.

To implement this, I'll be adding to the algorithm types using the parameters. The first change is pretty simple, and they algorithm types will be:

- CVODE_BDF{Method,LinearSolver} : This will do the BDF + the method and the linear solver. The recommended will be as the manual recommends: CVODE_BDF{:Newton,:Dense}, and will leave the option for adding more linear solver methods to expose.
- CVODE_Adams{Method,LinearSolver} : This will do Adams + the method and the linear solver. The recommended will be as the manual recommends: CVODE_Adams{:Functional,:None}. Note that really no second argument is required when `:Functional` is chosen.

This will allow the different options to be exposed and will make the algorithms different at compile-time, keeping their runtime performance.

**Comment by ChrisRackauckas** [comment]
Hmm, @dpsanders pointed out these kinds of defaults choices would be automatic if we used the type instance instead of the type:

http://stackoverflow.com/questions/40687337/making-a-no-parameter-type-have-defaults/40688493#40688493

@mauro3 what was the objection to using the type instance?

**Comment by mauro3** [comment]
I'd argue that those two setting should be part of the keyword arguments.  The way I see it is that a solver should be the "method", say one particular DOPRI implementation.  In the instance of Sundials I think it should have the solvers CVODE_BDF, CVODE_Adams, IDA, ARKode.  All the other setting should be kw-options.

Whether you then want a option to become a parameters to dispatch on or just some setting in a options strcut, etc., is up to you.  But I think for the user it would be hard to remember which solver options are encoded in the type and which as kwargs.

So a general aglo type I would implement in PR49 would look like:
```
MyAlg{Parameters_which_the_user_may_set, uType, tType, Any_other_dispatch_para}
```
Above two would fall into the `Any_other_dispatch_para`.  `Parameters_which_the_user_may_set` could be when using a single type to RK methods and use labels for the different ones, say `MyAlg{:dopri5}`, although, I would provide a type-alias for this.

To finally answer your question: yes, we could use instances instead.  But, irrespective of using types vs instances, I still think that above should be kwargs.  But then if the instance-parameters don't match the kwargs, you'd have to re-instantiate the type inside `solve` to set the parameters right (which isn't the end of the world either).  So we might as well use the types instead as then any unset parameters can be set trivially:
```
julia> immutable T{A,B,C,D} end

julia> T{:a,:b}{:c,:d}
T{:a,:b,:c,:d}

julia> typealias TT{C,A} T{A,:b,C,:d}
T{A,:b,C,:d}

julia> TT{:cc,:aa}
T{:aa,:b,:cc,:d}
```

**Comment by ChrisRackauckas** [comment]
>Whether you then want a option to become a parameters to dispatch on or just some setting in a options strcut, etc., is up to you. But I think for the user it would be hard to remember which solver options are encoded in the type and which as kwargs.

Why? The are documented in completely difference places. One is on choosing a method or related methods in details, another is on options (where do I save? Turn a progressbar on?). It makes more sense to have a type-alias then a kwarg for them. Many times these methods will be specific to the algorithm, and so it would only make sense to document them them right here:

https://juliadiffeq.github.io/DiffEqDocs.jl/latest/solvers/ode_solve.html#Sundials.jl-1

Right next to where you make the choice: I choose BDF with Newton and a Banded solver. We wouldn't want to bloat "common solver options" with one-time use options. Even if they aren't one-time use and should be standardized a bit for a class of algorithms (choice of linear solver), it still doesn't make sense in the "common options" because that should be left for options which we can reasonably expect any algorithm to implement. We should expect any reasonable algorithm to allow control over printing,  but we shouldn't expect every Runge-Kutta algorithm to care about a choice between functional iteration

The only common options which are "algorithm-specific" are `autodiff` (which should be choice in the algorithms that allow it) and adaptive timestepping controls, which the vast majority of algorithms use (but maybe some of the choices should be algorithm-specific because they default in algorithm specific ways!).

Let's look at the logic here:

1. You set a keyword arg `solve(prob,CVODE_BDF;banded=:Dense)`. Great! That works.
2. But now that it's a keyword arg, every developer has to use a function barrier anytime that they use similar types in order to have this choice compile away (sometimes, in order to have reasonable looking code, you will need this to compile away to have type-stability. Example: choice of linear solver when choosing direct methods). This will also have dynamic dispatch. Ouch.
3. The developer/user wants to then make this so that way the types aren't computed each time. In some cases this may be a non-trivial calculation (setting up a very specific banded linear solver). They ask the developer for this. The developer, using a type in a sensible way to dispatch, is likely using the algorithm type (we are both using it for our ODE solvers, Sundials will use it, etc.). So now the developer needs a function to somehow construct the algorithm object. What should that function be? 
4. For this, we got `init(prob,CVODE_BDF;banded=:Dense...)`, but kind of dropped that idea because it would bloat a lot of the API. But is there a simple way every Julia user understand how to construct a type? That should be a constructor for the algorithm type since that's what we are doing! [And when I ask this question elsewhere](http://stackoverflow.com/questions/40687337/making-a-no-parameter-type-have-defaults/40690964#40690964) everyone think's I'm crazy because the clear answer is "you're constructing a type, why not use the constructor? **What we were thinking of as the `init` method is the algorithm type constructor in every shape an way**, and only exists because we disallow constructing the type.

In the end, we seem to require function barriers and allow for an `init` method to stop the dynamic dispatch in order to easily construct the type for usage multiple times, but have to separate the arguments being init'd on because they are too specific to be generally documented, and try to document them essentially as the constructor for the algorithm, but not really because we don't allow constructors.

I think that's it's very clear we made a design mistake. . That's clear, every Julia user would that the constructor would construct the type, and it would document smoothly.

>MyAlg{Parameters_which_the_user_may_set, uType, tType, Any_other_dispatch_para}

Why would you put `uType` and `tType` in there? That's redundant with the problem, which surely is still around because you need the function and the initial condition. The only reason why I can think of `uType` being related to the algorithm choice is if you wanted to use the fact that `uType` is sparse mean a different linear solver. But as we already get in the Sundials algorithms, `uType` doesn't actually have the information we want: linear solver choice needs to be more specific than `sparse` (what kind of sparse solver? What are the matrix properties? This isn't in the type information) vs `AbstractArray, use a dense solver`.  And in what ways are you choosing a different algorithm based on the `tType`?

>But then if the instance-parameters don't match the kwargs, you'd have to re-instantiate the type inside solve to set the parameters right (which isn't the end of the world either)

That's only a manufactured issue if you make them keyword args.

Maybe we should pull in some other opinions. We should get this sorted out now before this API choice settles. @pwl @dpsanders @musm .

**Comment by mauro3** [comment]
I think our differences come from the implementation of PR49 vs OrdinaryDiffEq.  In Pr49 we use the alg-type instance to hold the options and other info of a solver-algorithm. To construct this the problem instance `prob` is needed to figure out the types.  For instance, to figure out the type of a tableau you need the problem type, in particular the `tType` (or some variation thereof if you do units).  You do this differently, as you have the ODEIntegrator type, which also needs the problem type to be constructed (and features `tType`, etc. as parameters as the Alg-types in PR49).  As I said, PR49 is fine to go with alg-instances, we can always create the PR49 internal alg-types from those.

I suspect what this boils down to is where to put options.  My opinion is that the `kwargs` of `solve` should contain all options, i.e. common ones as well as solver specific ones.  Options which are not understood by a particular solver are just ignored.  You seem to be of the opinion that in the `kwargs` of `solve` only the common options should be, whereas options understood by only one solver should somehow be passed to the solver directly.  *This is the problem of this issue.*  If we use your option handling strategy, then we should indeed go down the alg-instance route and a call to solve may look like `solve(prob, MyAlg(opt1=4, opt2=5); c_opt1=1, c_opt2=2)`.  

The problems I see with your approach are:
- the distinction between common and solver specific options is fairly arbitrary: namely whether an option has been standardized and documented or not.  This is illustrated by the fact, that not all solvers understand all the current common options, for instance fixed-step solvers.
- Going down this road will make updating of code potentially harder, say `opt2` gets included in the common options, now you have to re-write above to `solve(prob, MyAlg(opt1=4); c_opt1=1, c_opt2=2, opt2=5)`.
- the type-parameters of some `MyAlg` types may still need to be taylored to the type of `prob`, thus potentially necessitating re-construction of the MyAlg instance inside `solve` after all. 

A few comments:
- Concerning function barriers: one is needed anyway inside `solve` as kwargs defeat inference:
```
julia> f(x; y=1) = x+y

julia> Base.Test.@inferred f(5, y=8.0)
ERROR: return type Float64 does not match inferred return type Any
 in error(::String) at ./error.jl:21
```
- constructing a type with a function which is not the type itself is common in Julia, e.g. `zero`, `zeros`, `keys`, etc.


>> But then if the instance-parameters don't match the kwargs, you'd have to re-instantiate the type inside solve to set the parameters right (which isn't the end of the world either)

> That's only a manufactured issue if you make them keyword args.

Consider:
```
type MyAlg{tType}
  ...
end
...
# now a user has a problem with type
prob::ODEProblem{U1,T1}
# and would need to call
solve(prob, MyAlg{get_tType(prob)}(....); kwargs...)
```
Not so nice either.

**Comment by mauro3** [comment]
If others could give their opinion on where to put the options, that would be great. (we can still discuss separately on whether passing in an instance of Alg or the type)
```julia
solve(prob, Alg; kwargs...) # kwargs contains common options and specific ones
solve(prob, Alg(kwargs1...); kwargs2...) # kwargs1: specific; kwargs2: common
```
(also here the [link](https://juliadiffeq.github.io/DiffEqDocs.jl/latest/basics/common_solver_opts.html) to the common options)

To just vote use :heart:  for option 1, :+1: for option 2.

**Comment by ChrisRackauckas** [comment]
>Concerning function barriers: one is needed anyway inside solve as kwargs defeat inference

That likely will be going away with carneval's PR. However, if setting options which depend on value (like LinearSolver=:Dense), it will always have this problem.

>This is the problem of this issue. If we use your option handling strategy, then we should indeed go down the alg-instance route and a call to solve may look like solve(prob, MyAlg(opt1=4, opt2=5); c_opt1=1, c_opt2=2).

Yes, I agree that this is what it boils down to: whether everything should be keyword arguments for purity, or whether some algorithm-specific arguments should be handled by constructing the algorithm. Neither is really a showstopper.

**Comment by Datseris** [comment]
My vote: pass by type , eg. `Tsit5` instead of by constructor `Tsit5()`. It is just a humble vote, though! Don't take it by heart!

**Comment by mauro3** [comment]
Looks like we're going with option 2.  One big benefit of 2, as Chris mentioned above, is that code is more readable as one knows where to look for the documentation of the options.

However, I think that also for option 2 it would be more user friendly to have all options as kwargs.  Otherwise I'd have to remember whether `dense` was a type-parameter or key-word, etc.  Yes, this comes at some potential expense for the developer but user should come first.  (Also concerning type-stability in a future where kwargs are type-stable: my experience is that it is hard to write setup-code in a type-stable manner.  So often a function barrier is the easiest option anyway.)

Then the interface for `Alg` types would be that `Alg(;kwargs...)` is defined.  I think we can leave it to the package what will be returned from running this.  For PR49, we'd probably let it return a dict.  In the spirit of code-readability, it should probably be an error if a Alg gets a keyword it doesn't recognize.  Also, probably common-options shouldn't be allowed for extra solver options.

Then for `solve` only common-keywords are allowed, others error.  If we don't error this convenient but readability-defeating pattern could be used:
```
solve(prob, Alg(;dict_of_all_options...); dict_of_all_options...)
```

**Comment by ChrisRackauckas** [comment]
>Otherwise I'd have to remember whether dense was a type-parameter or key-word, etc.

That makes no sense. `dense` doesn't make it a different algorithm: it's not a different code path, it's just a way of saving. We're just preventing combinatoric explosion of algorithms. Most algorithms won't need to use this (but it would still be useful for them to store default overrides). If you look at PR49, you're essentially already trying to do this with `RKIntegrator{FoA,Coefficients}`, but requiring users to set parameters for the tableau, but don't provide a default because of exactly this issue: you can't provide default type parameters. If you just used `RKIntegrator()`, then you'd have the default be Dormand-Prince coefficients, with the other choices something someone can find listed where `RKIntegrator` is in the documentation. Or you could require that coefficients are given. This makes PR49 succinct to document: It's a generic RKIntegrator and a ModifiedRosenbrockIntegrator. `RKIntegrator(tab=DEFAULT_TABLEAU)` takes a tableau, that's fully specifies the code paths, and that's all that truly needs to be initialized.

The problem with then making every single variant a different algorithm comes quickly when variants are cheap to implement. PR49 has two algorithms which very in coefficients. While you don't offer very many tableaus so it doesn't need like a problem right now, if you took [a few minutes to link it to the full set of tableaus](https://github.com/JuliaDiffEq/DiffEqDevTools.jl/blob/master/src/ode_tableaus.jl) you'll suddenly have "about a hundred methods". We don't need to pollute the namespace with hundreds of methods especially when only a few should really be used (ex: Fehlburg methods never be used except for research on algorithm inefficiencies). They're all variants on the same algorithm, so they should be documented as variants and people should be given an easy (and Julian) way to specify variants of the same type. Again, if you ask StackOverflow what the way to do this in Julia is, everyone responds the same way: a constructor.

>Then the interface for Alg types would be that Alg(;kwargs...) is defined. I think we can leave it to the package what will be returned from running this. For PR49, we'd probably let it return a dict. In the spirit of code-readability, it should probably be an error if a Alg gets a keyword it doesn't recognize. Also, probably common-options shouldn't be allowed for extra solver options.

The algorithms should just error. You're far overthinking this. For most algorithms this is probably empty. I think when you see it in action you'll see why this doesn't make sense.

**Comment by mauro3** [comment]
I don't quite understand your points and I suspect you may not be understanding mine.  I just tried to argue that for the user it would be easier if the algorithm constructor (used as second argument to `solve`) would always have the form `Alg(;kwargs...)`.  Whether that then returns a type-instance which as parameter or not does not matter.  But if you feel that is too much of a restriction then let's have it free-from, so it can have type parameters and positional arguments too: `Alg{Para1,Para2,...}(args...; kwargs...)` and just document what's what.

> You're far overthinking this.

Yes, I do that at times :smile:.

**Comment by ChrisRackauckas** [comment]
>I just tried to argue that for the user it would be easier if the algorithm constructor (used as second argument to solve) would always have the form Alg(;kwargs...). Whether that then returns a type-instance which as parameter or not does not matter. 

That's what I was planning. Yes it doesn't matter what it returns, as long it's what solve takes. In many cases, it will probably just be a default constructor which will work just fine (all of the ODEInterface algorithms will just be like `dopri5()`, etc., my RK algorithms are just `Tsit5()`). But this is just a nicer way to handle `CVODE_BDF{Method,LinearSolver}` as `CVODE_BDF()` with `CVODE_BDF(method=...,linearsolver=...)` and be able to parse it. If anything, using a function instead of a bunch of type parameters is more powerful (it's a function).

And I think that's the main reason to try it though. It's strictly more powerful, and we can always scale back how much we use it. It could just be parsing some arguments to make a type with some parameters like what I was proposing here. But going the other way (only allowing specifying the type, but wanting to check the type parameters to make sure they're valid) is much more difficult (it pollutes the `solve` method, or you make another dispatch on `solve` just to put parameters on a type which makes it very clear there should've been a constructor involved).

The other thing is that it matches the other ecosystems. Optim.jl, JuMP, and JuliaML started with symbols, went to types, and now are at type instances. I know Tom has a bunch of reasons for why it's done this way in StochasticOptimization.jl, and Optim spent a lot of time to get it there as well (JuMP's been there for awhile). I don't think I completely know all of the reasons yet why they went there, but think we should learn from that.

Lastly, I think that you brought up a very valid point of restricting the options. 

>Also, probably common-options shouldn't be allowed for extra solver options.

That likely should be the case. They should basically be: "how do algorithms choose a step, save, and log what's going on". We have a good list, we should pull `autodiff` out of there as an implementation detail that only applies to a few algorithms, and leave it as a nice simple list of controls. 

This would leave a package open to document some crazy constructor for their for specific algorithm. This makes also makes it possible for an algorithm to have a docstring with a Documenter page for its constructor, internal checks to make sure everything is correct. This should lead to much more succinct documentation (and algorithm setups). And that's why I am now thinking that your problem of "where to put the kwargs" is a non-issue: the level of specificity that should be going into the algorithm constructor is something that you almost surely have to be looking at documentation or a docstring to know.

Here's a question: when using JuMP or Optim, have you ever not known where to put a keyword argument? The answer for me is no.

**Comment by ChrisRackauckas** [comment]
>To clarify, I tried to argue to always provide, for user convenience, a constructor `function Alg(;kwargs...)`

Yes, this is precisely what I am asking for and looking to do. And it's exactly what [Optim.jl](http://www.juliaopt.org/Optim.jl/latest/algo/newton_trust_region/) and what [the JuMP ecosystem does in order to allow the complexity of the algorithms provided by external sources](https://github.com/JuliaOpt/Ipopt.jl). I think they've shown it works well.

**Comment by mauro3** [comment]
>> To clarify, I tried to argue to always provide, for user convenience, a constructor function Alg(;kwargs...)

> Yes, this is precisely what I am asking for and looking to do. And it's exactly what Optim.jl and what the JuMP ecosystem does in order to allow the complexity of the algorithms provided by external sources. I think they've shown it works well.

Aright, let's do it!

**Comment by ChrisRackauckas** [comment]
Finished #98
